name: Python application

on: [push]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ 'ubuntu-20.04', 'macos-11', 'windows-2019' ]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download test
      run: |
        python antenati.py https://www.antenati.san.beniculturali.it/detail-registry/?s_id=19944549
